server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-report
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
# DB EN AWS
    url: jdbc:mysql://db.ctd.academy:3306/pi21023c01_GRUPO6
    username: pi21023c01_GRUPO6
    password: toXae4Pi
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          import_files: report-service.sql

info:
  application:
    name: api-report

eureka:
  instance:
    hostname: report
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/


springdoc:
  api-docs:
    path: /report/api-docs
  swagger-ui:
    path: /report/swagger