server:
  port: ${PORT:${SERVER_PORT:8081}}

spring:
  application:
    name: event-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

    # DB EN AWS
#    url: jdbc:mysql://db.ctd.academy:3306/pi21023c01_GRUPO6
#    username: pi21023c01_GRUPO6
#    password: toXae4Pi

    #DB LOCAL
    url: jdbc:mysql://localhost:3333/event-db
    username: event-user
    password: event-password
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files: user.sql