#--------------- Configuration Local ----------------------#

# Server configuration
server:
  port: 8081

# Spring configuration
spring:
  application:
    name: ms-gateway
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/
      client:
        provider:
          keycloak:
            authorization-uri: http://keycloak:8080/
            token-uri: http://keycloak:8080/realms
            user-name-attribute: preferred_username
            user-info-uri: http://keycloak:8080/realms
            jwk-set-uri: http://keycloak:8080/realms
            user-info-authentication-method: header
        registration:
          gateway:
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8081/login/oauth2/code/keycloak
            provider: keycloak
            clientId: gateway
            clientSecret:
            scope: openid, profile
  cloud:
    gateway:
      routes:
        - id: ms-accounts
          uri: lb://ms-accounts
          predicates:
            - Path=/api/v1/accounts/**
        - id: ms-user
          uri: lb://ms-user
          predicates:
            - Path=/api/v1/users/**
        - id: ms-cards
          uri: lb://ms-cards
          predicates:
            - Path=/api/v1/cards/**
        - id: ms-middleware
          uri: lb://ms-middleware
          predicates:
            - Path=/api/v1/transactions/**
      default-filters:
        - TokenRelay=
        - StripPrefix=2
#        - name: CircuitBreaker
#          args:
#            name: circuitBreaker
#            fallbackUri: forward:/api/v1/fallback

# Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

## Management configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
## Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO