#--------------- Configuration Local ----------------------#

# Server configuration
server:
  port: ${PORT:${SERVER_PORT:8080}}

# Spring configuration
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-event
          uri: lb://api-event
          predicates:
            - Path=/event/**
        - id: api-user
          uri: lb://api-user
          predicates:
            - Path=/user/**
        - id: api-subscription
          uri: lb://api-subscription
          predicates:
            - Path=/subscription/**

info:
  app:
    name: gateway

# Eureka configuration
eureka:
  instance:
    hostname: gateway
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

## Management configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
## Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO


#--------------- Configuration Docker ----------------------#
#spring:
#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          jwk-set-uri: http://${KEYCLOAK_HOST}:8080/realms
#      client:
#        provider:
#          keycloak:
#            authorization-uri: http://${KEYCLOAK_FRONT_HOST}:8080/realms
#            token-uri: http://${KEYCLOAK_HOST}:8080/realms
#            user-info-uri: http://${KEYCLOAK_HOST}:8080/realms
#            jwk-set-uri: http://${KEYCLOAK_HOST}:8080/realms
#        registration:
#          gateway:
#            redirectUri: http://${KEYCLOAK_FRONT_HOST}:8081/login/oauth2/code/keycloak
# Eureka configuration
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:8761/eureka
#
### Logging configuration
#logging:
#  level:
#    org.springframework.cloud.gateway: INFO
#    reactor.netty.http.client: INFO