#--------------- Configuration Local ----------------------#

# Server configuration
server:
  port: 8761

# Spring configuration
spring:
  application:
    name: eureka-server-service

# Eureka configuration
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false