#--------------- Configuration Local ----------------------#

# Server configuration
server:
  port: ${PORT:${SERVER_PORT:8080}}

# Spring configuration
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-event
          uri: lb://api-event
          predicates:
            - Path=/**
        - id: api-user
          uri: lb://api-user
          predicates:
            - Path=/user/**

info:
  app:
    name: gateway

# Eureka configuration
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

## Management configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
## Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO