#--------------- Configuration Docker ----------------------#
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST}:8080/realms/digitalMoneyHouse/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            authorization-uri: http://${KEYCLOAK_FRONT_HOST}:8080/realms/digitalMoneyHouse/protocol/openid-connect/auth
            token-uri: http://${KEYCLOAK_HOST}:8080/realms/digitalMoneyHouse/protocol/openid-connect/token
            user-info-uri: http://${KEYCLOAK_HOST}:8080/realms/digitalMoneyHouse/protocol/openid-connect/userinfo
            jwk-set-uri: http://${KEYCLOAK_HOST}:8080/realms/digitalMoneyHouse/protocol/openid-connect/certs
        registration:
          gateway:
            redirectUri: http://${KEYCLOAK_FRONT_HOST}:8081/login/oauth2/code/keycloak
# Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

## Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO