#--------------- Configuration Local ----------------------#

# Server configuration
server:
  port: ${PORT:8761}

# Spring configuration
spring:
  application:
    name: eureka-server

# Eureka configuration
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/