server:
  port: ${PORT:${SERVER_PORT:8081}}

spring:
  application:
    name: api-event
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3333/event-db
    username: event-user
    password: event-password
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files: event-service.sql

info:
  application:
    name: api-event

eureka:
  health-check:
    enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path=/api-docs: