server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: subscription-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

    # DB EN AWS
    url: jdbc:mysql://db.ctd.academy:3306/pi21023c01_GRUPO6
    username: pi21023c01_GRUPO6
    password: toXae4Pi

    # DB LOCAL
#    url: jdbc:mysql://localhost:3333/event-db
#    username: event-user
#    password: event-password

  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files: subscription-service.sql

info:
  application:
    name: api-subscription

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


springdoc:
  api-docs:
    path: /subscription/api-docs
  swagger-ui:
    path: /subscription/swagger